stages:
  - build

variables:
  VERSION: 0.1.0-$CI_COMMIT_SHORT_SHA-snapshot

build:
  stage: build
  parallel:
    matrix:
      - APP_TYPE: [backend, admin, web]
  variables:
    IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/$APP_TYPE
    IMAGE_TAG: $VERSION
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - git submodule update --init --recursive --remote
    - docker build -t $IMAGE:$VERSION . -f docker/Dockerfile.$APP_TYPE 
    - docker push $IMAGE:$VERSION