stages:
  - build
  - deploy

variables:
  VERSION: 0.1.0-$CI_COMMIT_SHORT_SHA-snapshot

build-prod:
  stage: build
  parallel:
    matrix:
      - APP_TYPE: [backend, admin, web]
  variables:
    IMAGE: gitlab.sigma-it.ru:4567/sigma-chat-doc/registry/$APP_TYPE
    IMAGE_TAG: $VERSION-prod
  script:
    - echo "$WRITE_REGISTRY_TOKEN" | docker login $CI_REGISTRY -u
      "write_registry" --password-stdin
    - git submodule update --init --recursive --remote
    - docker build -t $IMAGE:$VERSION . -f docker/Dockerfile.$APP_TYPE
    - docker push $IMAGE:$VERSION
    - docker build -t $IMAGE:$IMAGE_TAG . -f docker/Dockerfile.$APP_TYPE
    - docker push $IMAGE:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:
build-test:
  stage: build
  parallel:
    matrix:
      - APP_TYPE: [backend, admin, web]
  variables:
    IMAGE: gitlab.sigma-it.ru:4567/sigma-chat-doc/registry/$APP_TYPE
    IMAGE_TAG: $VERSION-test
  script:
    - echo "$WRITE_REGISTRY_TOKEN" | docker login $CI_REGISTRY -u
      "write_registry" --password-stdin
    - git submodule update --init --recursive --remote
    - docker build -t $IMAGE:$IMAGE_TAG . -f docker/Dockerfile.$APP_TYPE
      --build-arg NODE_ENV=test --build-arg VITE_MODE=test
    - docker push $IMAGE:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

deploy-prod:
  stage: deploy
  image: docker-group.sigma-it.ru/kroniak/ssh-client
  variables:
    IMAGE_TAG: $VERSION-prod
  before_script:
    - chmod 400 "$SSH_PRIVATE_KEY"
  script:
    - ssh -o StrictHostKeychecking=no -i "$SSH_PRIVATE_KEY"
      user@dpis-scd1.sigma-it.local "cd demo-stand-deploy && sed -i
      \"s/^\(.*APP_VERSION=\).*/\1${VERSION}/\" .env && docker compose up -d"
    - ssh -o StrictHostKeychecking=no -i "$SSH_PRIVATE_KEY"
      user@dpis-scd1.sigma-it.local "cd dev-stand-deploy && sed -i
      \"s/^\(.*APP_VERSION=\).*/\1${IMAGE_TAG}/\" .env && docker compose up -d"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - build-prod

deploy-test:
  stage: deploy
  image: docker-group.sigma-it.ru/kroniak/ssh-client
  variables:
    IMAGE_TAG: $VERSION-test
  before_script:
    - chmod 400 "$SSH_PRIVATE_KEY_TEST"
  script:
    - ssh -o StrictHostKeychecking=no -i "$SSH_PRIVATE_KEY_TEST"
      user@dpis-ai2.sigma-it.local "cd demo-stand-deploy && sed -i
      \"s/^\(.*APP_VERSION=\).*/\1${IMAGE_TAG}/\" .env && docker compose up -d"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  needs:
    - build

    - build-test
