FROM gitlab.sigma-it.ru:4567/mkuznetsov/sigmachat/node:22.14.0 as base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder
WORKDIR /app
RUN pnpm install --global turbo@2.3.3
COPY . .
RUN turbo prune @repo/web --docker

FROM base AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --ignore-scripts

COPY --from=builder /app/out/full/ .

RUN pnpm run build:web

FROM gitlab.sigma-it.ru:4567/mkuznetsov/sigmachat/nginx:1.25-alpine AS runner

USER root

RUN mkdir -p /var/cache/nginx && chown -R nginx:nginx /var/cache/nginx && \
    mkdir -p /var/run/nginx && chown -R nginx:nginx /var/run/nginx

COPY --from=installer --chown=nginx:nginx /app/apps/web/dist/client /usr/share/nginx/html

USER nginx

# expose port 8080
EXPOSE 8080

# run nginx
CMD ["nginx", "-g", "daemon off;"]