FROM gitlab.sigma-it.ru:4567/mkuznetsov/sigmachat/node:22.14.0 as base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder
WORKDIR /app
RUN pnpm install --global turbo@2.3.3
COPY . .
RUN turbo prune @repo/backend --docker

FROM base AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --ignore-scripts

COPY --from=builder /app/out/full/ .

RUN pnpm run build:backend

FROM base AS runner
WORKDIR /app
 
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs
USER nodejs
 
COPY --from=installer --chown=nodejs:nodejs /app/packages/backend/dist ./packages/backend/dist/
COPY --from=installer --chown=nodejs:nodejs /app/packages/backend/node_modules ./packages/backend/node_modules/
COPY --from=installer --chown=nodejs:nodejs /app/node_modules ./node_modules/

CMD ["node", "packages/backend/dist/main"]