#map $http_origin $allow_origin {
#    ~^https://(stage|mm\.)?ray.sx $http_origin;
#}

server {
    listen 80 default;
    server_name _;
    root /var/www/admin-app/public;
    index index.html;
    location / {
          try_files $uri $uri.html;
    }
    location /api {
        include /etc/nginx/options.request.conf;
        include /etc/nginx/proxy.settings.conf;
        proxy_pass http://192.168.1.102:3000;
    }
}
