version: '3.7'

services:

  minio:
    image: minio/minio
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - media:/data
    environment:
      MINIO_ROOT_USER: 8VUKTW1WH9ER56OTO9Y
      MINIO_ROOT_PASSWORD: LRHKD9EUJ9WQMRHYILNKRJN8O8W

    command: server --address ":8080" --console-address ":9090" /data

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    privileged: true
    restart: always

  nginx:
    image: bardakdev/rifify-nginx
    restart: always
    links:
      - backend
#      - certbot
    volumes:
      - certbot:/certbot
    ports:
      - "80:80"
      - "443:443"
    privileged: true

#  certbot:
#    image: bardakdev/rifify-certbot
#    volumes:
#      - certbot:/certbot

  backend:
    image: bardakdev/rifify-backend
    restart: always
    depends_on:
      - mongo
      - redis
      - minio
    links:
      - mongo
      - redis
      - minio
    command: [ "npm", "run", "dev" ]

  mongo:
    privileged: true
    image: bardakdev/mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
      - MONGO_INITDB_DATABASE=rifify
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongo-db:/data/db
      - mongo-db-config:/data/configdb
    command: [ --replSet, rs0, --bind_ip_all, --port, "27017", --keyFile, "/opt/keyfile" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}).ok || rs.status().ok" | /usr/bin/mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s

  redis:
    image: redis:alpine
    restart: always
    privileged: true
    volumes:
      - redis:/data
    sysctls:
      net.core.somaxconn: 65535
    command: "/bin/sh -c redis-server & echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' > /etc/rc.local"

networks:
  default:
    name: "rifify"

volumes:
  media:
    name: "rifify_media"
  mongo-db:
    name: "rifify_mongo-db"
  mongo-db-config:
    name: "rifify_mongo-db-config"
  redis:
    name: "rifify_redis"
  certbot:
    name: "rifify_certbot"

