services:

#  mongo:
#    privileged: true
#    image: bardakdev/mongo
#    container_name: mongo
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root123
#      - MONGO_INITDB_DATABASE=rifify
#      - MONGO_REPLICA_SET_NAME=rs0
#    volumes:
#      - mongo-db:/data/db
#      - mongo-db-config:/data/configdb
#
#    command: [ --replSet, rs0, --bind_ip_all, --port, "27017", --keyFile, "/opt/keyfile" ]
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    ports:
#      - "27017:27017"
#    healthcheck:
#      test: |
#        test $$(mongosh --quiet -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --eval "try { rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'mongo:27017' } ] }).ok } catch (_) { rs.status().ok }") -eq 1
#      interval: 10s
#      start_period: 30s
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"

  redis:
    image: redis:alpine
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    sysctls:
      net.core.somaxconn: 65535
    command: "/bin/sh -c redis-server --requirepass redis123 & echo 'echo never > 
    /sys/kernel/mm/transparent_hugepage/enabled' > /etc/rc
    .local"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio
    ports:
      - "8090:8080"
      - "9090:9000"
    volumes:
      - media:/data
    environment:
      MINIO_ROOT_USER: 8VUKTW1WH9ER56OTO9Y
      MINIO_ROOT_PASSWORD: LRHKD9EUJ9WQMRHYILNKRJN8O8W

    command: server --address ":8080" --console-address ":9000" /data

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    links:
      - postgres

networks:
  default:
    name: "rf"

volumes:
  mongo-db:
    name: "sc_mongo-db"
  mongo-db-config:
    name: "sc_mongo-db-config"
  redis:
    name: "sc_redis"
  media:
    name: "sc_media"
  postgres:
    name: "sc_media"
  pgadmin:
    name: "sc_pgadmin"
