services:
  redis:
    image: redis:alpine
    container_name: redis_sigmachat
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    # sysctls:
    #   net.core.somaxconn: 65535
    command:
      "/bin/sh -c 'redis-server --requirepass redis123' & echo 'echo never >
      /sys/kernel/mm/transparent_hugepage/enabled' > /etc/rc.local"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio
    ports:
      - "8090:8080"
      - "9090:9000"
    volumes:
      - media:/data
    environment:
      MINIO_ROOT_USER: 8VUKTW1WH9ER56OTO9Y
      MINIO_ROOT_PASSWORD: LRHKD9EUJ9WQMRHYILNKRJN8O8W

    command: server --address ":8080" --console-address ":9000" /data

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    environment:
      GOTENBERG_API_BASIC_AUTH_USERNAME: "root"
      GOTENBERG_API_BASIC_AUTH_PASSWORD: "root123"

      GOTENBERG_API_PORT: "3000"
      GOTENBERG_API_ENABLE_BASIC_AUTH: "true"
      GOTENBERG_API_BODY_LIMIT: "5GB"

    command:
      - "gotenberg"
      - "--api-enable-basic-auth"

    links:
      - minio

networks:
  default:
    name: "rf"

volumes:
  mongo-db:
    name: "sc_mongo-db"
  mongo-db-config:
    name: "sc_mongo-db-config"
  redis:
    name: "sc_redis"
  media:
    name: "sc_media"
  postgres:
    name: "postgres"
  pgadmin:
    name: "sc_pgadmin"
